### ISSUE TITLE
One of setGitDir or setWorkTree must be called.

### ISSUE THREAD

**Issue by suresh-s** [tomahawk-player/tomahawk-android#75] opened 2016-11-11 14:04 UTC
I am getting following issue while compiling the code.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sureshs/Downloads/tomahawk-android-master/gradle/script/git-version.gradle' line: 35

* What went wrong:
A problem occurred evaluating script.
> One of setGitDir or setWorkTree must be called.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by theli-ua** [comment] 2016-11-13 05:29
this is a duplicate of issue#67

**Closed by theli-ua** 2016-11-13 05:29 UTC
